packages:
  - "packages/*"
  - "deployers/*"
  - "stores/*"
  - "voice/*"
  - "workflows/*"
  - "pubsub/*"
  - "client-sdks/*"
  - "integrations/*"
  - "examples/dane"
  - "examples/opencog-distributed-agency"
  - "packages/*/integration-tests"
  - "packages/*/integration-tests-v5"
  - "auth/*"
  - "observability/*"
  - "explorations/longmemeval"
  - "explorations/agent-builder-gh-repro"
