// export const trace = {
//   id: '156d98aaea15df7d',
//   name: "workflow run: 'my-workflow'",
//   input: {
//     ingredient: 'avocado',
//   },
//   output: {
//     result: 'guacamole',
//   },
//         metadata: {
//   spanType: 'workflow_run',
//   workflowId: 'my-workflow',
//   status: 'success',
// },
//   createdAt: '2025-08-15T17:05:08Z',
// };

export const trace = {
  id: '156d98aaea15df7d',
  projectId: 'cmdei6e8i0wa4ad07mzya8yjk',
  name: "workflow run: 'my-workflow'",
  timestamp: '2025-08-15T15:05:08.722Z',
  environment: 'default',
  tags: [],
  bookmarked: false,
  release: null,
  version: null,
  userId: null,
  sessionId: null,
  public: false,
  input: '"{\\"ingredient\\":\\"avocado\\"}"',
  output: '"{\\"result\\":\\"suh\\"}"',
  metadata: {
    spanType: 'workflow_run',
    workflowId: 'my-workflow',
    status: 'success',
  },
  createdAt: '2025-08-15T15:05:08.722Z',
  updatedAt: '2025-08-15T15:05:35.384Z',
  scores: [],
  latency: 21.338,
  observations: [
    {
      id: '4280755c92319de9',
      traceId: '156d98aaea15df7d',
      projectId: 'cmdei6e8i0wa4ad07mzya8yjk',
      type: 'SPAN',
      environment: 'default',
      parentObservationId: '42c51d88ae58f982',
      startTime: '2025-08-15T15:05:08.736Z',
      endTime: '2025-08-15T15:05:30.048Z',
      name: "agent run: 'Chef Agent Responses'",
      metadata: {
        spanType: 'agent_run',
        agentId: 'Chef Agent Responses',
        instructions:
          '\n    You are Michel, a practical and experienced home chef who helps people cook great meals with whatever\n    ingredients they have available. Your first priority is understanding what ingredients and equipment the user has access to, then suggesting achievable recipes.\n    You explain cooking steps clearly and offer substitutions when needed, maintaining a friendly and encouraging tone throughout.\n    ',
        availableTools: [],
        runId: '90ccf436-fe5d-4587-8b71-1cf7cdb0c944',
        usage: {
          promptTokens: 886,
          completionTokens: 217,
          totalTokens: 1103,
        },
        toolResults: [],
        toolCalls: [],
      },
      level: 'DEFAULT',
      statusMessage: null,
      version: null,
      input: null,
      output: {
        text: "Great! Let's make something delicious with Oreos. Here are a few ideas:\n\n### Oreo Mug Cake\n\n**Ingredients:**\n- 4 Oreos\n- 1/4 cup milk\n- 1/4 teaspoon baking powder (optional for fluffiness)\n\n**Instructions:**\n1. **Crush the Oreos:** Place the Oreos in a microwave-safe mug and crush them with a spoon until they are in small pieces.\n2. **Add Milk:** Pour the milk over the crushed Oreos and stir until you have a smooth mixture.\n3. **Add Baking Powder:** If you want a fluffier cake, add the baking powder and mix well.\n4. **Microwave:** Microwave the mug on high for about 1-2 minutes, or until the cake has set.\n5. **Enjoy:** Let it cool slightly before digging in!\n\nFeel free to add a scoop of ice cream or a drizzle of chocolate syrup on top for extra indulgence. Enjoy your treat!",
      },
      modelParameters: null,
      completionStartTime: null,
      promptId: null,
      createdAt: '2025-08-15T15:05:10.000Z',
      updatedAt: '2025-08-15T15:05:35.384Z',
      usageDetails: {},
      costDetails: {},
      providedCostDetails: {},
      model: null,
      internalModelId: null,
      promptName: null,
      promptVersion: null,
      latency: 21312,
      timeToFirstToken: null,
      inputCost: null,
      outputCost: null,
      totalCost: 0,
      inputUsage: 0,
      outputUsage: 0,
      totalUsage: 0,
    },
    {
      id: '42c51d88ae58f982',
      traceId: '156d98aaea15df7d',
      projectId: 'cmdei6e8i0wa4ad07mzya8yjk',
      type: 'SPAN',
      environment: 'default',
      parentObservationId: '156d98aaea15df7d',
      startTime: '2025-08-15T15:05:08.733Z',
      endTime: '2025-08-15T15:05:30.053Z',
      name: "workflow step: 'my-step-2'",
      metadata: {
        spanType: 'workflow_run',
        workflowId: 'my-workflow',
        status: 'success',
      },
      level: 'DEFAULT',
      statusMessage: null,
      version: null,
      input: {
        ingredient: 'avocado',
      },
      output: {
        result: 'suh',
      },
      modelParameters: null,
      completionStartTime: null,
      promptId: null,
      createdAt: '2025-08-15T15:05:09.000Z',
      updatedAt: '2025-08-15T15:05:35.378Z',
      usageDetails: {},
      costDetails: {},
      providedCostDetails: {},
      model: null,
      internalModelId: null,
      promptName: null,
      promptVersion: null,
      latency: 21320,
      timeToFirstToken: null,
      inputCost: null,
      outputCost: null,
      totalCost: 0,
      inputUsage: 0,
      outputUsage: 0,
      totalUsage: 0,
    },
    {
      id: 'c48eeb713afba06e',
      traceId: '156d98aaea15df7d',
      projectId: 'cmdei6e8i0wa4ad07mzya8yjk',
      type: 'GENERATION',
      environment: 'default',
      parentObservationId: '4280755c92319de9',
      startTime: '2025-08-15T15:05:25.399Z',
      endTime: '2025-08-15T15:05:30.046Z',
      name: "llm generate: 'gpt-4o'",
      metadata: {
        spanType: 'workflow_run',
        workflowId: 'my-workflow',
        status: 'success',
      },
      level: 'DEFAULT',
      statusMessage: null,
      version: null,
      input: {
        ingredient: 'avocado',
      },
      output: {
        result: 'suh',
      },
      modelParameters: {
        temperature: 0,
      },
      completionStartTime: null,
      promptId: null,
      createdAt: '2025-08-15T15:05:26.000Z',
      updatedAt: '2025-08-15T15:05:35.371Z',
      usageDetails: {
        input: 303,
        output: 55,
        total: 358,
      },
      costDetails: {
        input: 0.0007575,
        output: 0.00055,
        total: 0.0013075,
      },
      providedCostDetails: {},
      model: 'gpt-4o',
      internalModelId: 'b9854a5c92dc496b997d99d20',
      promptName: null,
      promptVersion: null,
      latency: 4647,
      timeToFirstToken: null,
      inputCost: 0.0007575,
      outputCost: 0.00055,
      totalCost: 0.0013075,
      inputUsage: 303,
      outputUsage: 55,
      totalUsage: 358,
    },
    {
      id: '156d98aaea15df7d',
      traceId: '156d98aaea15df7d',
      projectId: 'cmdei6e8i0wa4ad07mzya8yjk',
      type: 'SPAN',
      environment: 'default',
      parentObservationId: null,
      startTime: '2025-08-15T15:05:08.722Z',
      endTime: '2025-08-15T15:05:30.060Z',
      name: "workflow run: 'my-workflow'",
      metadata: {
        spanType: 'workflow_run',
        workflowId: 'my-workflow',
        status: 'success',
      },
      level: 'DEFAULT',
      statusMessage: null,
      version: null,
      input: {
        ingredient: 'avocado',
      },
      output: {
        result: 'suh',
      },
      modelParameters: null,
      completionStartTime: null,
      promptId: null,
      createdAt: '2025-08-15T15:05:09.000Z',
      updatedAt: '2025-08-15T15:05:35.351Z',
      usageDetails: {},
      costDetails: {},
      providedCostDetails: {},
      model: null,
      internalModelId: null,
      promptName: null,
      promptVersion: null,
      latency: 21338,
      timeToFirstToken: null,
      inputCost: null,
      outputCost: null,
      totalCost: 0,
      inputUsage: 0,
      outputUsage: 0,
      totalUsage: 0,
    },
    {
      id: '9e4a7a2b92ab9351',
      traceId: '156d98aaea15df7d',
      projectId: 'cmdei6e8i0wa4ad07mzya8yjk',
      type: 'SPAN',
      environment: 'default',
      parentObservationId: '7ce0ea9e62702a92',
      startTime: '2025-08-15T15:05:10.411Z',
      endTime: '2025-08-15T15:05:25.396Z',
      name: "workflow run: 'my-workflow'",
      metadata: {
        spanType: 'workflow_run',
        workflowId: 'my-workflow',
        status: 'success',
      },
      level: 'DEFAULT',
      statusMessage: null,
      version: null,
      input: {
        ingredient: 'avocado',
      },
      output: {
        result: 'suh',
      },
      modelParameters: null,
      completionStartTime: null,
      promptId: null,
      createdAt: '2025-08-15T15:05:11.000Z',
      updatedAt: '2025-08-15T15:05:30.799Z',
      usageDetails: {},
      costDetails: {},
      providedCostDetails: {},
      model: null,
      internalModelId: null,
      promptName: null,
      promptVersion: null,
      latency: 14985,
      timeToFirstToken: null,
      inputCost: null,
      outputCost: null,
      totalCost: 0,
      inputUsage: 0,
      outputUsage: 0,
      totalUsage: 0,
    },
    {
      id: '7ce0ea9e62702a92',
      traceId: '156d98aaea15df7d',
      projectId: 'cmdei6e8i0wa4ad07mzya8yjk',
      type: 'SPAN',
      environment: 'default',
      parentObservationId: '4280755c92319de9',
      startTime: '2025-08-15T15:05:10.409Z',
      endTime: '2025-08-15T15:05:25.396Z',
      name: "create workflow tool: 'myWorkflow'",
      metadata: {
        spanType: 'workflow_run',
        workflowId: 'my-workflow',
        status: 'success',
      },
      level: 'DEFAULT',
      statusMessage: null,
      version: null,
      input: {
        ingredient: 'avocado',
      },
      output: {
        result: 'suh',
      },
      modelParameters: null,
      completionStartTime: null,
      promptId: null,
      createdAt: '2025-08-15T15:05:11.000Z',
      updatedAt: '2025-08-15T15:05:30.788Z',
      usageDetails: {},
      costDetails: {},
      providedCostDetails: {},
      model: null,
      internalModelId: null,
      promptName: null,
      promptVersion: null,
      latency: 14987,
      timeToFirstToken: null,
      inputCost: null,
      outputCost: null,
      totalCost: 0,
      inputUsage: 0,
      outputUsage: 0,
      totalUsage: 0,
    },
    {
      id: '6094ad79e187a7ea',
      traceId: '156d98aaea15df7d',
      projectId: 'cmdei6e8i0wa4ad07mzya8yjk',
      type: 'GENERATION',
      environment: 'default',
      parentObservationId: '299a85f64ab3cb15',
      startTime: '2025-08-15T15:05:16.712Z',
      endTime: '2025-08-15T15:05:25.387Z',
      name: "llm generate: 'gpt-4o'",
      metadata: {
        spanType: 'workflow_run',
        workflowId: 'my-workflow',
        status: 'success',
      },
      level: 'DEFAULT',
      statusMessage: null,
      version: null,
      input: {
        ingredient: 'avocado',
      },
      output: {
        result: 'suh',
      },
      modelParameters: {
        temperature: 0,
      },
      completionStartTime: null,
      promptId: null,
      createdAt: '2025-08-15T15:05:17.000Z',
      updatedAt: '2025-08-15T15:05:30.760Z',
      usageDetails: {
        input: 303,
        output: 50,
        total: 353,
      },
      costDetails: {
        input: 0.0007575,
        output: 0.0005,
        total: 0.0012575,
      },
      providedCostDetails: {},
      model: 'gpt-4o',
      internalModelId: 'b9854a5c92dc496b997d99d20',
      promptName: null,
      promptVersion: null,
      latency: 8675,
      timeToFirstToken: null,
      inputCost: 0.0007575,
      outputCost: 0.0005,
      totalCost: 0.0012575,
      inputUsage: 303,
      outputUsage: 50,
      totalUsage: 353,
    },
    {
      id: '299a85f64ab3cb15',
      traceId: '156d98aaea15df7d',
      projectId: 'cmdei6e8i0wa4ad07mzya8yjk',
      type: 'SPAN',
      environment: 'default',
      parentObservationId: 'a5c25dbf18fb7dcc',
      startTime: '2025-08-15T15:05:10.418Z',
      endTime: '2025-08-15T15:05:25.389Z',
      name: "agent run: 'Chef Agent Responses'",
      metadata: {
        spanType: 'workflow_run',
        workflowId: 'my-workflow',
        status: 'success',
      },
      level: 'DEFAULT',
      statusMessage: null,
      version: null,
      input: {
        ingredient: 'avocado',
      },
      output: {
        result: 'suh',
      },
      modelParameters: null,
      completionStartTime: null,
      promptId: null,
      createdAt: '2025-08-15T15:05:11.000Z',
      updatedAt: '2025-08-15T15:05:30.739Z',
      usageDetails: {},
      costDetails: {},
      providedCostDetails: {},
      model: null,
      internalModelId: null,
      promptName: null,
      promptVersion: null,
      latency: 14971,
      timeToFirstToken: null,
      inputCost: null,
      outputCost: null,
      totalCost: 0,
      inputUsage: 0,
      outputUsage: 0,
      totalUsage: 0,
    },
    {
      id: 'a5c25dbf18fb7dcc',
      traceId: '156d98aaea15df7d',
      projectId: 'cmdei6e8i0wa4ad07mzya8yjk',
      type: 'SPAN',
      environment: 'default',
      parentObservationId: '9e4a7a2b92ab9351',
      startTime: '2025-08-15T15:05:10.415Z',
      endTime: '2025-08-15T15:05:25.392Z',
      name: "workflow step: 'my-step-2'",
      metadata: {
        spanType: 'workflow_run',
        workflowId: 'my-workflow',
        status: 'success',
      },
      level: 'DEFAULT',
      statusMessage: null,
      version: null,
      input: {
        ingredient: 'avocado',
      },
      output: {
        result: 'suh',
      },
      modelParameters: null,
      completionStartTime: null,
      promptId: null,
      createdAt: '2025-08-15T15:05:11.000Z',
      updatedAt: '2025-08-15T15:05:30.729Z',
      usageDetails: {},
      costDetails: {},
      providedCostDetails: {},
      model: null,
      internalModelId: null,
      promptName: null,
      promptVersion: null,
      latency: 14977,
      timeToFirstToken: null,
      inputCost: null,
      outputCost: null,
      totalCost: 0,
      inputUsage: 0,
      outputUsage: 0,
      totalUsage: 0,
    },
    {
      id: '10a0ac90424df9a2',
      traceId: '156d98aaea15df7d',
      projectId: 'cmdei6e8i0wa4ad07mzya8yjk',
      type: 'SPAN',
      environment: 'default',
      parentObservationId: 'b353cb5f8aefd7e0',
      startTime: '2025-08-15T15:05:11.353Z',
      endTime: '2025-08-15T15:05:16.707Z',
      name: "workflow run: 'my-workflow'",
      metadata: {
        spanType: 'workflow_run',
        workflowId: 'my-workflow',
        status: 'success',
      },
      level: 'DEFAULT',
      statusMessage: null,
      version: null,
      input: {
        ingredient: 'avocado',
      },
      output: {
        result: 'suh',
      },
      modelParameters: null,
      completionStartTime: null,
      promptId: null,
      createdAt: '2025-08-15T15:05:12.000Z',
      updatedAt: '2025-08-15T15:05:22.073Z',
      usageDetails: {},
      costDetails: {},
      providedCostDetails: {},
      model: null,
      internalModelId: null,
      promptName: null,
      promptVersion: null,
      latency: 5354,
      timeToFirstToken: null,
      inputCost: null,
      outputCost: null,
      totalCost: 0,
      inputUsage: 0,
      outputUsage: 0,
      totalUsage: 0,
    },
    {
      id: '2d4d72570e5e9a09',
      traceId: '156d98aaea15df7d',
      projectId: 'cmdei6e8i0wa4ad07mzya8yjk',
      type: 'SPAN',
      environment: 'default',
      parentObservationId: '10a0ac90424df9a2',
      startTime: '2025-08-15T15:05:11.358Z',
      endTime: '2025-08-15T15:05:16.701Z',
      name: "workflow step: 'my-step-2'",
      metadata: {
        spanType: 'workflow_run',
        workflowId: 'my-workflow',
        status: 'success',
      },
      level: 'DEFAULT',
      statusMessage: null,
      version: null,
      input: {
        ingredient: 'avocado',
      },
      output: {
        result: 'suh',
      },
      modelParameters: null,
      completionStartTime: null,
      promptId: null,
      createdAt: '2025-08-15T15:05:12.000Z',
      updatedAt: '2025-08-15T15:05:22.070Z',
      usageDetails: {},
      costDetails: {},
      providedCostDetails: {},
      model: null,
      internalModelId: null,
      promptName: null,
      promptVersion: null,
      latency: 5343,
      timeToFirstToken: null,
      inputCost: null,
      outputCost: null,
      totalCost: 0,
      inputUsage: 0,
      outputUsage: 0,
      totalUsage: 0,
    },
    {
      id: 'b353cb5f8aefd7e0',
      traceId: '156d98aaea15df7d',
      projectId: 'cmdei6e8i0wa4ad07mzya8yjk',
      type: 'SPAN',
      environment: 'default',
      parentObservationId: '299a85f64ab3cb15',
      startTime: '2025-08-15T15:05:11.352Z',
      endTime: '2025-08-15T15:05:16.707Z',
      name: "create workflow tool: 'myWorkflow'",
      metadata: {
        spanType: 'workflow_run',
        workflowId: 'my-workflow',
        status: 'success',
      },
      level: 'DEFAULT',
      statusMessage: null,
      version: null,
      input: {
        ingredient: 'avocado',
      },
      output: {
        result: 'suh',
      },
      modelParameters: null,
      completionStartTime: null,
      promptId: null,
      createdAt: '2025-08-15T15:05:12.000Z',
      updatedAt: '2025-08-15T15:05:22.035Z',
      usageDetails: {},
      costDetails: {},
      providedCostDetails: {},
      model: null,
      internalModelId: null,
      promptName: null,
      promptVersion: null,
      latency: 5355,
      timeToFirstToken: null,
      inputCost: null,
      outputCost: null,
      totalCost: 0,
      inputUsage: 0,
      outputUsage: 0,
      totalUsage: 0,
    },
    {
      id: '6c7976e9ad76b644',
      traceId: '156d98aaea15df7d',
      projectId: 'cmdei6e8i0wa4ad07mzya8yjk',
      type: 'SPAN',
      environment: 'default',
      parentObservationId: '2d4d72570e5e9a09',
      startTime: '2025-08-15T15:05:11.360Z',
      endTime: '2025-08-15T15:05:16.696Z',
      name: "agent run: 'Chef Agent Responses'",
      metadata: {
        spanType: 'workflow_run',
        workflowId: 'my-workflow',
        status: 'success',
      },
      level: 'DEFAULT',
      statusMessage: null,
      version: null,
      input: {
        ingredient: 'avocado',
      },
      output: {
        result: 'suh',
      },
      modelParameters: null,
      completionStartTime: null,
      promptId: null,
      createdAt: '2025-08-15T15:05:12.000Z',
      updatedAt: '2025-08-15T15:05:22.031Z',
      usageDetails: {},
      costDetails: {},
      providedCostDetails: {},
      model: null,
      internalModelId: null,
      promptName: null,
      promptVersion: null,
      latency: 5336,
      timeToFirstToken: null,
      inputCost: null,
      outputCost: null,
      totalCost: 0,
      inputUsage: 0,
      outputUsage: 0,
      totalUsage: 0,
    },
    {
      id: '6e8e32ea0f609374',
      traceId: '156d98aaea15df7d',
      projectId: 'cmdei6e8i0wa4ad07mzya8yjk',
      type: 'GENERATION',
      environment: 'default',
      parentObservationId: '6c7976e9ad76b644',
      startTime: '2025-08-15T15:05:11.365Z',
      endTime: '2025-08-15T15:05:16.695Z',
      name: "llm generate: 'gpt-4o'",
      metadata: {
        spanType: 'workflow_run',
        workflowId: 'my-workflow',
        status: 'success',
      },
      level: 'DEFAULT',
      statusMessage: null,
      version: null,
      input: {
        ingredient: 'avocado',
      },
      output: {
        result: 'suh',
      },
      modelParameters: {
        temperature: 0,
      },
      completionStartTime: null,
      promptId: null,
      createdAt: '2025-08-15T15:05:12.000Z',
      updatedAt: '2025-08-15T15:05:22.024Z',
      usageDetails: {
        input: 101,
        output: 51,
        total: 152,
      },
      costDetails: {
        input: 0.0002525,
        output: 0.00051,
        total: 0.0007625,
      },
      providedCostDetails: {},
      model: 'gpt-4o',
      internalModelId: 'b9854a5c92dc496b997d99d20',
      promptName: null,
      promptVersion: null,
      latency: 5330,
      timeToFirstToken: null,
      inputCost: 0.0002525,
      outputCost: 0.00051,
      totalCost: 0.0007625,
      inputUsage: 101,
      outputUsage: 51,
      totalUsage: 152,
    },
    {
      id: '8f899bcfef3dd9a1',
      traceId: '156d98aaea15df7d',
      projectId: 'cmdei6e8i0wa4ad07mzya8yjk',
      type: 'SPAN',
      environment: 'default',
      parentObservationId: '10a0ac90424df9a2',
      startTime: '2025-08-15T15:05:11.353Z',
      endTime: '2025-08-15T15:05:11.354Z',
      name: "workflow step: 'my-step'",
      metadata: {
        spanType: 'workflow_run',
        workflowId: 'my-workflow',
        status: 'success',
      },
      level: 'DEFAULT',
      statusMessage: null,
      version: null,
      input: {
        ingredient: 'avocado',
      },
      output: {
        result: 'suh',
      },
      modelParameters: null,
      completionStartTime: null,
      promptId: null,
      createdAt: '2025-08-15T15:05:12.000Z',
      updatedAt: '2025-08-15T15:05:16.697Z',
      usageDetails: {},
      costDetails: {},
      providedCostDetails: {},
      model: null,
      internalModelId: null,
      promptName: null,
      promptVersion: null,
      latency: 1,
      timeToFirstToken: null,
      inputCost: null,
      outputCost: null,
      totalCost: 0,
      inputUsage: 0,
      outputUsage: 0,
      totalUsage: 0,
    },
    {
      id: '0b3359c29d16f0a1',
      traceId: '156d98aaea15df7d',
      projectId: 'cmdei6e8i0wa4ad07mzya8yjk',
      type: 'GENERATION',
      environment: 'default',
      parentObservationId: '299a85f64ab3cb15',
      startTime: '2025-08-15T15:05:10.427Z',
      endTime: '2025-08-15T15:05:11.350Z',
      name: "llm generate: 'gpt-4o'",
      metadata: {
        spanType: 'workflow_run',
        workflowId: 'my-workflow',
        status: 'success',
      },
      level: 'DEFAULT',
      statusMessage: null,
      version: null,
      input: {
        ingredient: 'avocado',
      },
      output: {
        result: 'suh',
      },
      modelParameters: {
        temperature: 0,
      },
      completionStartTime: null,
      promptId: null,
      createdAt: '2025-08-15T15:05:11.000Z',
      updatedAt: '2025-08-15T15:05:16.652Z',
      usageDetails: {
        input: 101,
        output: 53,
        total: 154,
      },
      costDetails: {
        input: 0.0002525,
        output: 0.00053,
        total: 0.0007825,
      },
      providedCostDetails: {},
      model: 'gpt-4o',
      internalModelId: 'b9854a5c92dc496b997d99d20',
      promptName: null,
      promptVersion: null,
      latency: 923,
      timeToFirstToken: null,
      inputCost: 0.0002525,
      outputCost: 0.00053,
      totalCost: 0.0007825,
      inputUsage: 101,
      outputUsage: 53,
      totalUsage: 154,
    },
    {
      id: '44555b8e4ff2e57b',
      traceId: '156d98aaea15df7d',
      projectId: 'cmdei6e8i0wa4ad07mzya8yjk',
      type: 'GENERATION',
      environment: 'default',
      parentObservationId: '4280755c92319de9',
      startTime: '2025-08-15T15:05:08.744Z',
      endTime: '2025-08-15T15:05:10.408Z',
      name: "llm generate: 'gpt-4o'",
      metadata: {
        spanType: 'workflow_run',
        workflowId: 'my-workflow',
        status: 'success',
      },
      level: 'DEFAULT',
      statusMessage: null,
      version: null,
      input: {
        ingredient: 'avocado',
      },
      output: {
        result: 'suh',
      },
      modelParameters: {
        temperature: 0,
      },
      completionStartTime: null,
      promptId: null,
      createdAt: '2025-08-15T15:05:09.000Z',
      updatedAt: '2025-08-15T15:05:15.725Z',
      usageDetails: {
        input: 101,
        output: 57,
        total: 158,
      },
      costDetails: {
        input: 0.0002525,
        output: 0.00057,
        total: 0.0008225,
      },
      providedCostDetails: {},
      model: 'gpt-4o',
      internalModelId: 'b9854a5c92dc496b997d99d20',
      promptName: null,
      promptVersion: null,
      latency: 1664,
      timeToFirstToken: null,
      inputCost: 0.0002525,
      outputCost: 0.00057,
      totalCost: 0.0008225,
      inputUsage: 101,
      outputUsage: 57,
      totalUsage: 158,
    },
    {
      id: '95ed5080127be445',
      traceId: '156d98aaea15df7d',
      projectId: 'cmdei6e8i0wa4ad07mzya8yjk',
      type: 'SPAN',
      environment: 'default',
      parentObservationId: '9e4a7a2b92ab9351',
      startTime: '2025-08-15T15:05:10.411Z',
      endTime: '2025-08-15T15:05:10.412Z',
      name: "workflow step: 'my-step'",
      metadata: {
        spanType: 'workflow_run',
        workflowId: 'my-workflow',
        status: 'success',
      },
      level: 'DEFAULT',
      statusMessage: null,
      version: null,
      input: {
        ingredient: 'avocado',
      },
      output: {
        result: 'suh',
      },
      modelParameters: null,
      completionStartTime: null,
      promptId: null,
      createdAt: '2025-08-15T15:05:11.000Z',
      updatedAt: '2025-08-15T15:05:15.716Z',
      usageDetails: {},
      costDetails: {},
      providedCostDetails: {},
      model: null,
      internalModelId: null,
      promptName: null,
      promptVersion: null,
      latency: 1,
      timeToFirstToken: null,
      inputCost: null,
      outputCost: null,
      totalCost: 0,
      inputUsage: 0,
      outputUsage: 0,
      totalUsage: 0,
    },
    {
      id: 'cdafbafe0f21857c',
      traceId: '156d98aaea15df7d',
      projectId: 'cmdei6e8i0wa4ad07mzya8yjk',
      type: 'SPAN',
      environment: 'default',
      parentObservationId: '156d98aaea15df7d',
      startTime: '2025-08-15T15:05:08.722Z',
      endTime: '2025-08-15T15:05:08.724Z',
      name: "workflow step: 'my-step'",
      metadata: {
        spanType: 'workflow_run',
        workflowId: 'my-workflow',
        status: 'success',
      },
      level: 'DEFAULT',
      statusMessage: null,
      version: null,
      input: {
        ingredient: 'avocado',
      },
      output: {
        result: 'suh',
      },
      modelParameters: null,
      completionStartTime: null,
      promptId: null,
      createdAt: '2025-08-15T15:05:09.000Z',
      updatedAt: '2025-08-15T15:05:14.165Z',
      usageDetails: {},
      costDetails: {},
      providedCostDetails: {},
      model: null,
      internalModelId: null,
      promptName: null,
      promptVersion: null,
      latency: 2,
      timeToFirstToken: null,
      inputCost: null,
      outputCost: null,
      totalCost: 0,
      inputUsage: 0,
      outputUsage: 0,
      totalUsage: 0,
    },
  ],
};
