import { cn } from '@/lib/utils';
import {
  HeaderTitle,
  Header,
  MainContentLayout,
  EntryList,
  ObservabilityTracesTools,
  PageHeader,
} from '@mastra/playground-ui';
import { useState } from 'react';
// import { useWorkflows } from '@/hooks/use-workflows';
import { useAgents } from '@/hooks/use-agents';
import { EyeIcon } from 'lucide-react';
import { useTrace } from './useTrace';
import { TraceDialog } from './TraceDialog';

export default function observability() {
  const { trace, nestedSpans, spans, spanIds } = useTrace();
  const [selectedTrace, setSelectedTrace] = useState<any>(null);
  const [selectedEntity, setSelectedEntity] = useState<string | undefined>(undefined);
  const [selectedDateFrom, setSelectedDateFrom] = useState<Date | null | undefined>(undefined);
  const [selectedDateTo, setSelectedDateTo] = useState<Date | null | undefined>(undefined);
  const [dialogIsOpen, setDialogIsOpen] = useState<boolean>(false);
  const { data: agents, isLoading: agentsLoading } = useAgents();
  // const { data: workflows, isLoading: workflowsLoading } = useWorkflows();

  const entities = [
    ...(Object.entries(agents) || []).map(([key, value]) => ({ id: key, name: value.name, type: 'agent' })),
    // ...(workflows || []).map(workflow => ({ id: workflow.id, name: workflow.name, type: 'workflow' })),
  ];
  const entityOptions = entities.map(entity => ({ value: entity.id, label: entity.name }));

  const handleReset = () => {
    setSelectedTrace(null);
    setSelectedEntity('');
    setDialogIsOpen(false);
    setSelectedDateFrom(undefined);
    setSelectedDateTo(undefined);
  };

  const handleEntityChange = (value: string) => {
    setSelectedEntity(value || '');
  };

  const handleDataChange = (value: Date | null | undefined, type: 'from' | 'to') => {
    console.log({ value, type });

    if (type === 'from') {
      setSelectedDateFrom(value);
    } else {
      setSelectedDateTo(value);
    }
  };

  const events = [
    {
      id: 'a392r13f',
      date: '2023-10-01',
      time: '12:00:00',
      input: 'Sample input text for AI model.',
      output: 'Sample output text generated by AI model.',
      createdAt: '2023-10-01T12:00:00Z',
      entityId: 'chefAgent',
      entityType: 'agent',
      entityName: entities.find(entity => entity.id === 'chefAgent')?.name || 'n/a',
    },
    {
      id: '1398r132',
      date: '2023-10-02',
      time: '13:00:00',
      input: 'Another sample input text for testing.',
      output: 'Another sample output text generated by AI model.',
      createdAt: '2023-10-02T13:00:00Z',
      entityId: 'chefAgent',
      entityType: 'agent',
      entityName: entities.find(entity => entity.id === 'chefAgent')?.name || 'n/a',
    },
    {
      id: 'a123b456',
      date: '2023-10-03',
      time: '14:00:00',
      input: 'Input text for AI model processing.',
      output: 'Output text generated by AI model.',
      createdAt: '2023-10-03T14:00:00Z',
      entityId: 'evalAgent',
      entityType: 'agent',
      entityName: entities.find(entity => entity.id === 'evalAgent')?.name || 'n/a',
    },
  ];

  const filteredEvents = events.filter(event => {
    if (selectedEntity) {
      const entity = entities.find(entity => entity.id === selectedEntity);

      if (entity && event.entityId !== entity.id) {
        return false;
      }
    }
    return true;
  });

  const listColumns = [
    { name: 'id', label: 'ID', size: '5rem' },
    { name: 'date', label: 'Date', size: '5rem' },
    { name: 'time', label: 'Time', size: '5rem' },
    { name: 'entityName', label: 'Entity', size: '8rem' },
    { name: 'input', label: 'Input', size: '1fr' },
  ];

  const handleOnListItem = (id: string) => {
    console.log('handleOnListItem', id, selectedTrace?.id);

    if (id === selectedTrace?.id) {
      setSelectedTrace(null);
    } else {
      const item = events.find(item => item.id === id);

      if (!item) {
        console.warn('Item not found for id:', id);
        return;
      }

      setSelectedTrace(item);
      setDialogIsOpen(true);
    }
  };

  const toPreviousItem = (currentEvent: any) => {
    const currentIndex = events?.findIndex(event => event?.id === currentEvent?.id);
    if (currentIndex === -1 || currentIndex === (events?.length || 0) - 1) {
      return null; // No next event
    }
    return () => setSelectedTrace(events[(currentIndex || 0) + 1]);
  };

  const toNextItem = (currentEvent: any) => {
    const currentIndex = events?.findIndex(event => event?.id === currentEvent?.id);
    if ((currentIndex || 0) <= 0) {
      return null; // No previous event
    }
    return () => setSelectedTrace(events[(currentIndex || 0) - 1]);
  };

  return (
    <>
      <MainContentLayout>
        <Header>
          <HeaderTitle>Observability</HeaderTitle>
        </Header>

        <div className={cn(`h-full overflow-y-scroll `)}>
          <div className={cn('max-w-[100rem] px-[3rem] mx-auto grid gap-[2rem]')}>
            <PageHeader title="Observability" description="View and manage observability events." icon={<EyeIcon />} />
            <ObservabilityTracesTools
              onEntityChange={handleEntityChange}
              onReset={handleReset}
              selectedEntity={selectedEntity}
              entityOptions={entityOptions}
              onDateChange={handleDataChange}
              selectedDateFrom={selectedDateFrom}
              selectedDateTo={selectedDateTo}
            />
            <EntryList
              items={filteredEvents}
              selectedItem={selectedTrace}
              onItemClick={handleOnListItem}
              columns={listColumns}
              isLoading={false}
            />
          </div>
        </div>
      </MainContentLayout>
      <TraceDialog
        isOpen={dialogIsOpen}
        onClose={() => setDialogIsOpen(false)}
        onNext={toNextItem(selectedTrace)}
        onPrevious={toPreviousItem(selectedTrace)}
        trace={trace}
        spans={spans || []}
        nestedSpans={nestedSpans}
        spanIds={spanIds}
      />
    </>
  );
}
