import { cn } from '@/lib/utils';
import {
  HeaderTitle,
  Header,
  MainContentLayout,
  EntryList,
  ObservabilityEventDialog,
  ObservabilityEventsTools,
  PageHeader,
} from '@mastra/playground-ui';
import { useState } from 'react';
// import { useWorkflows } from '@/hooks/use-workflows';
import { useAgents } from '@/hooks/use-agents';
import { Eye, EyeIcon } from 'lucide-react';

export default function observability() {
  const [selectedEvent, setSelectedEvent] = useState<any>(null);
  const [selectedEntity, setSelectedEntity] = useState<number | undefined>(undefined);
  const [dialogIsOpen, setDialogIsOpen] = useState<boolean>(false);
  const { agents, isLoading: agentsLoading } = useAgents();
  // const { data: workflows, isLoading: workflowsLoading } = useWorkflows();
  const entities = [
    ...(Object.entries(agents) || []).map(([key, value]) => ({ id: key, name: value.name, type: 'agent' })),
    // ...(workflows || []).map(workflow => ({ id: workflow.id, name: workflow.name, type: 'workflow' })),
  ];
  const entityOptions = entities.map(entity => entity.name);

  const handleReset = () => {
    setSelectedEvent(null);
    setSelectedEntity(undefined);
    setDialogIsOpen(false);
  };

  const handleEntityChange = (value: string) => {
    setSelectedEntity(value ? parseInt(value, 10) : undefined);
  };

  const events = [
    {
      id: 'a392r13f',
      date: '2023-10-01',
      time: '12:00:00',
      input: 'Sample input text for AI model.',
      output: 'Sample output text generated by AI model.',
      createdAt: '2023-10-01T12:00:00Z',
      entityId: 'chefAgent',
      entityType: 'agent',
      entityName: entities.find(entity => entity.id === 'chefAgent')?.name || 'n/a',
    },
    {
      id: '1398r132',
      date: '2023-10-02',
      time: '13:00:00',
      input: 'Another sample input text for testing.',
      output: 'Another sample output text generated by AI model.',
      createdAt: '2023-10-02T13:00:00Z',
      entityId: 'chefAgent',
      entityType: 'agent',
      entityName: entities.find(entity => entity.id === 'chefAgent')?.name || 'n/a',
    },
    {
      id: 'a123b456',
      date: '2023-10-03',
      time: '14:00:00',
      input: 'Input text for AI model processing.',
      output: 'Output text generated by AI model.',
      createdAt: '2023-10-03T14:00:00Z',
      entityId: 'evalAgent',
      entityType: 'agent',
      entityName: entities.find(entity => entity.id === 'evalAgent')?.name || 'n/a',
    },
  ];

  const filteredEvents = events.filter(event => {
    if (typeof selectedEntity === 'number' && selectedEntity >= 0) {
      const entity = entities?.[selectedEntity];

      if (entity && event.entityId !== entity.id) {
        return false;
      }
    }
    return true;
  });

  console.log('Filtering event:', filteredEvents);

  const listColumns = [
    { name: 'id', label: 'ID', size: '4rem' },
    { name: 'date', label: 'Date', size: '5rem' },
    { name: 'time', label: 'Time', size: '5rem' },
    { name: 'entityName', label: 'Entity', size: '8rem' },
    { name: 'input', label: 'Input', size: '1fr' },
  ];

  const handleOnListItem = (id: string) => {
    if (id === selectedEvent?.id) {
      setSelectedEvent(null);
    } else {
      const item = events.find(item => item.id === id);

      if (!item) {
        console.warn('Item not found for id:', id);
        return;
      }

      setSelectedEvent(item);
      setDialogIsOpen(true);
    }
  };

  const toPreviousItem = (currentEvent: any) => {
    const currentIndex = events?.findIndex(event => event?.id === currentEvent?.id);
    if (currentIndex === -1 || currentIndex === (events?.length || 0) - 1) {
      return null; // No next event
    }
    return () => setSelectedEvent(events[(currentIndex || 0) + 1]);
  };

  const toNextItem = (currentEvent: any) => {
    const currentIndex = events?.findIndex(event => event?.id === currentEvent?.id);
    if ((currentIndex || 0) <= 0) {
      return null; // No previous event
    }
    return () => setSelectedEvent(events[(currentIndex || 0) - 1]);
  };

  return (
    <>
      <MainContentLayout>
        <Header>
          <HeaderTitle>Observability</HeaderTitle>
        </Header>

        <div className={cn(`h-full overflow-y-scroll `)}>
          <div className={cn('max-w-[100rem] px-[3rem] mx-auto grid gap-[2rem]')}>
            <PageHeader title="Observability" description="View and manage observability events." icon={<EyeIcon />} />
            <ObservabilityEventsTools
              onEntityChange={handleEntityChange}
              onReset={handleReset}
              selectedEntity={selectedEntity?.toString() || ''}
              entityOptions={entityOptions}
            />
            <EntryList
              items={filteredEvents}
              selectedItem={selectedEvent}
              onItemClick={handleOnListItem}
              columns={listColumns}
              isLoading={false}
            />
          </div>
        </div>
      </MainContentLayout>
      <ObservabilityEventDialog
        isOpen={dialogIsOpen}
        event={selectedEvent}
        onClose={() => setDialogIsOpen(false)}
        onNext={toNextItem(selectedEvent)}
        onPrevious={toPreviousItem(selectedEvent)}
      />
    </>
  );
}
