name: Build All Packages (No Skip)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force build all packages'
        required: false
        default: 'true'
        type: boolean

jobs:
  build-all:
    name: Build All Packages
    runs-on: ubuntu-latest
    # Always run this workflow - no conditional skipping
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_CACHE: remote:rw
      NODE_OPTIONS: --max-old-space-size=4096
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          # Fetch entire git history for better turbo cache
          fetch-depth: 0

      - name: Configure npm registry
        run: mkdir -p ~/setup-pnpm && echo "registry=https://registry.yarnpkg.com" > ~/setup-pnpm/.npmrc

      - uses: wardpeet/action-setup@pnpm-registry
        name: Install pnpm
        with:
          registry: https://registry.yarnpkg.com
          run_install: false

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.1
          cache: 'pnpm'
          registry-url: 'https://registry.yarnpkg.com'

      - name: Install dependencies
        run: pnpm install

      - name: Build all packages (no filtering)
        run: pnpm build

      - name: Type check all packages
        run: pnpm typecheck

      - name: Lint all packages
        run: pnpm lint

      - name: Build Summary
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "✅ All packages built successfully without skipping" >> $GITHUB_STEP_SUMMARY
          echo "- All packages: ✅" >> $GITHUB_STEP_SUMMARY
          echo "- Type checking: ✅" >> $GITHUB_STEP_SUMMARY
          echo "- Linting: ✅" >> $GITHUB_STEP_SUMMARY